# --- Stage 1: Build the application with Maven and Java 21 ---
FROM maven:3.9.6-eclipse-temurin-21 AS build
WORKDIR /usr/src/app

# Copy the pom.xml to cache dependencies, then copy the source code
COPY pom.xml .
COPY src ./src

# Package the application using the Quarkus fast-jar format
RUN mvn clean package -DskipTests

# --- Stage 2: Ultra-lightweight JRE 21 Runtime ---
FROM eclipse-temurin:21-jre-alpine
WORKDIR /deployments

# Copy the specific fast-jar layout generated by Quarkus 3.34.6
COPY --from=build /usr/src/app/target/quarkus-app/lib/ /deployments/lib/
COPY --from=build /usr/src/app/target/quarkus-app/*.jar /deployments/
COPY --from=build /usr/src/app/target/quarkus-app/app/ /deployments/app/
COPY --from=build /usr/src/app/target/quarkus-app/quarkus/ /deployments/quarkus/

EXPOSE 8080

# Environment configurations for container optimization
ENV JAVA_OPTIONS="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"

ENTRYPOINT ["java", "-jar", "/deployments/quarkus-run.jar"]