
quarkus.langchain4j.ai.gemini.api-key=API-TOKEN

quarkus.langchain4j.chat-model.provider=ai-gemini
quarkus.langchain4j.ai.gemini.chat-model.model-id=gemini-2.5-flash

#quarkus.langchain4j.ai.gemini.chat-model.temperature=0.2
#quarkus.langchain4j.ai.gemini.chat-model.top-p=0.9
#quarkus.langchain4j.chat-memory.memory-window.max-messages=20

quarkus.langchain4j.log-requests=true
quarkus.langchain4j.log-responses=true